campaign: SO284
campaign_id: SO284
platform: RV_Sonne
location: RV_Sonne
configs:
    main: config/main.yaml  # name of this file
    level0: config/level0_mwx.yml
    level1: config/level1.yaml
    level2: config/level2.yaml